{% set version = "0.29.2" %}

package:
  name: pkg-config
  version: {{ version }}

source:
  url: https://pkg-config.freedesktop.org/releases/pkg-config-{{ version }}.tar.gz
  sha256: 6fc69c01688c9458a57eb9a1664c9aba372ccda420a02bf4429fe610e7e7d591

build:
{% if bootstrapping == 'yes' %}
  # Please increment by two
  number: 0
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_bootstrapping
{% else %}
  # Keep above the number of the _bootstrapping package
  number: 1008
{% endif %}
  skip: True  # [win and vc<14]
  detect_binary_files_with_prefix: True
  script_env:
    - BOOTSTRAPPING={{ bootstrapping }}

requirements:
  build:
    - {{ compiler('c') }}
{% if bootstrapping != 'yes' %}
    - libtool  # [unix]
    - automake  # [unix]
    - make  # [unix]
  host:
    # To avoid a cyclic dependency when building, we avoid glib when not cross-compiling
    # This assumes that both pkg-config and glib are cross-compiled or neither is
    - glib  # [win or (build_platform != target_platform)]
    - libiconv  # [osx]
{% endif %}

test:
  commands:
    - pkg-config --help

about:
  home: http://www.freedesktop.org/wiki/Software/pkg-config/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Interface for querying installed libraries for use during compilation.

  description: |
    pkg-config is a script to make putting together all the build
    flags when compiling/linking a lot easier.
  doc_url: https://people.freedesktop.org/~dbn/pkg-config-guide.html
  dev_url: https://cgit.freedesktop.org/pkg-config
  doc_source_url:

extra:
  recipe-maintainers:
    - jakirkham
    - mdboom
    - ocefpaf
    - tacaswell
    - mingwandroid
